# -*- coding: utf-8 -*-
"""calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y23OcKQA4Nm0gl58W98-fSfe0sgKP7l1
"""

def add(a, b):
    return a + b


def subtract(a, b):
    return a - b


def multiply(a, b):
    return a * b


def divide(a, b):
    if b == 0:
        return "Error: Cannot divide by zero!"
    return a / b


def clear():
    print("\nCalculator cleared.\n")


def calculate(num1, num2, operator):
    if operator == "+":
        return add(num1, num2)

    elif operator == "-":
        return subtract(num1, num2)

    elif operator == "*":
        return multiply(num1, num2)

    elif operator == "/":
        return divide(num1, num2)

    else:
        return "Invalid operator!"


def main():
    while True:
        print("\n===== CALCULATOR MENU =====")
        print("1. Calculate")
        print("2. Clear")
        print("3. Exit")

        choice = input("Enter your choice (1-3): ")

        if choice == "1":
            try:
                num1 = float(input("Enter first number: "))
                operator = input("Enter operator (+, -, *, /): ")
                num2 = float(input("Enter second number: "))

                result = calculate(num1, num2, operator)
                print("Result:", result)

            except ValueError:
                print("Error: Please enter valid numbers.")

        elif choice == "2":
            clear()

        elif choice == "3":
            print("Exiting calculator...")
            break

        else:
            print("Invalid menu choice!")


if __name__ == "__main__":
    main()

