# -*- coding: utf-8 -*-
"""converter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1je5WmShmrLafNHxN2sbtxcKvvXuYyQBX
"""

import pandas as pd
import argparse
import logging
import os

os.makedirs("logs", exist_ok=True)
os.makedirs("output", exist_ok=True)

logging.basicConfig(
    filename="logs/converter.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

def clean_data(df):
    df = df.drop_duplicates()
    df = df.fillna("N/A")

    df.columns = [
        col.strip().lower().replace(" ", "_")
        for col in df.columns
    ]

    return df


def convert_csv_to_excel(input_file, output_file):
    try:
        logging.info(f"Reading file: {input_file}")

        df = pd.read_csv(input_file)

        logging.info("Cleaning data")
        df = clean_data(df)

        df.to_excel(output_file, index=False)

        logging.info(f"Excel file saved: {output_file}")

        print("Conversion Successful!")
        print("Output File:", output_file)

    except FileNotFoundError:
        logging.error("Input file not found")
        print("Error: File not found")

    except pd.errors.EmptyDataError:
        logging.error("CSV file is empty")
        print("Error: CSV file is empty")

    except Exception as e:
        logging.error(str(e))
        print("Unexpected Error:", e)


def main():
    parser = argparse.ArgumentParser(description="CSV to Excel Converter")

    parser.add_argument("--input", required=True, help="Path to input CSV file")
    parser.add_argument("--output", required=True, help="Path to output Excel file")

    args = parser.parse_args()

    convert_csv_to_excel(args.input, args.output)


if __name__ == "__main__":
    main()