# -*- coding: utf-8 -*-
"""number_guessing_game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RV9SMiP91PlWkgKk_YTxpjokwh2Dbjqf
"""

import random

best_score = None

while True:
    print("\n=== Number Guessing Game ===")
    print("Choose Difficulty:")
    print("1. Easy (1-10)")
    print("2. Medium (1-50)")
    print("3. Hard (1-100)")

    choice = input("Enter your choice (1/2/3): ")

    if choice == "1":
        max_num = 10
    elif choice == "2":
        max_num = 50
    elif choice == "3":
        max_num = 100
    else:
        print("Invalid choice!")
        continue

    secret_number = random.randint(1, max_num)
    attempts = 0

    print(f"\nI have chosen a number between 1 and {max_num}.")

    while True:
        guess = int(input("Enter your guess: "))
        attempts += 1

        if guess < secret_number:
            print("Higher!")

        elif guess > secret_number:
            print("Lower!")

        else:
            print(f"Correct! You guessed it in {attempts} attempts.")

            if best_score is None or attempts < best_score:
                best_score = attempts
                print(" New Best Score!")

            print("Best Score:", best_score)
            break

    replay = input("\nPlay again? (yes/no): ").lower()

    if replay != "yes":
        print("Thanks for playing!")
        break

