# -*- coding: utf-8 -*-
"""student_management_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwQ6A2Oa6dw7V7U5yvsM37VHz_X4YFFa
"""

import json
import os


class Student:
    def __init__(self, student_id, name, grade):
        self.student_id = student_id
        self.name = name
        self.grade = grade

    def to_dict(self):
        return {
            "id": self.student_id,
            "name": self.name,
            "grade": self.grade
        }


class StudentManager:
    def __init__(self, filename="students.json"):
        self.filename = filename
        self.students = []
        self.load_data()

    def load_data(self):
        if os.path.exists(self.filename):
            with open(self.filename, "r") as file:
                data = json.load(file)

                for student in data:
                    self.students.append(
                        Student(
                            student["id"],
                            student["name"],
                            student["grade"]
                        )
                    )

    def save_data(self):
        data = [student.to_dict() for student in self.students]

        with open(self.filename, "w") as file:
            json.dump(data, file, indent=4)

    def add_student(self, student_id, name, grade):
        for student in self.students:
            if student.student_id == student_id:
                print("Error: Student ID already exists!")
                return

        self.students.append(Student(student_id, name, grade))
        self.save_data()
        print("Student added successfully!")

    def update_student(self, student_id):
        for student in self.students:
            if student.student_id == student_id:
                student.name = input("Enter new name: ")
                student.grade = input("Enter new grade: ")

                self.save_data()
                print("Student updated successfully!")
                return

        print("Student not found!")

    def delete_student(self, student_id):
        for student in self.students:
            if student.student_id == student_id:
                self.students.remove(student)
                self.save_data()
                print("Student deleted successfully!")
                return

        print("Student not found!")

    def list_students(self):
        if not self.students:
            print("No students found.")
            return

        print("\n" + "=" * 40)
        print(f"{'ID':<10}{'NAME':<15}{'GRADE':<10}")
        print("=" * 40)

        for student in self.students:
            print(
                f"{student.student_id:<10}"
                f"{student.name:<15}"
                f"{student.grade:<10}"
            )

        print("=" * 40)


def main():
    manager = StudentManager()

    while True:
        print("\n===== STUDENT MANAGEMENT SYSTEM =====")
        print("1. Add Student")
        print("2. Update Student")
        print("3. Delete Student")
        print("4. List Students")
        print("5. Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            sid = input("Enter ID: ")
            name = input("Enter Name: ")
            grade = input("Enter Grade: ")

            manager.add_student(sid, name, grade)

        elif choice == "2":
            sid = input("Enter Student ID: ")
            manager.update_student(sid)

        elif choice == "3":
            sid = input("Enter Student ID: ")
            manager.delete_student(sid)

        elif choice == "4":
            manager.list_students()

        elif choice == "5":
            print("Goodbye!")
            break

        else:
            print("Invalid choice!")


if __name__ == "__main__":
    main()

