# -*- coding: utf-8 -*-
"""todo_list_manager

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X50UEfD58HJEFQlHWbZXh6y5FOM9TlAg
"""

FILE_NAME = "tasks.txt"


def add_task():
    task = input("Enter task: ")

    with open(FILE_NAME, "a") as file:
        file.write("[ ] " + task + "\n")

    print("Task added!")


def view_tasks():
    try:
        with open(FILE_NAME, "r") as file:
            tasks = file.readlines()

        if len(tasks) == 0:
            print("No tasks found.")
        else:
            print("\nTasks:")
            for i, task in enumerate(tasks, start=1):
                print(f"{i}. {task.strip()}")

    except FileNotFoundError:
        print("No tasks found.")


def mark_done():
    try:
        with open(FILE_NAME, "r") as file:
            tasks = file.readlines()

        view_tasks()

        num = int(input("Enter task number to mark done: "))

        if 1 <= num <= len(tasks):
            tasks[num - 1] = "[X] " + tasks[num - 1][4:]

            with open(FILE_NAME, "w") as file:
                file.writelines(tasks)

            print("Task marked as done!")
        else:
            print("Invalid task number.")

    except FileNotFoundError:
        print("No tasks found.")
    except ValueError:
        print("Enter a valid number.")


def delete_task():
    try:
        with open(FILE_NAME, "r") as file:
            tasks = file.readlines()

        view_tasks()

        num = int(input("Enter task number to delete: "))

        if 1 <= num <= len(tasks):
            tasks.pop(num - 1)

            with open(FILE_NAME, "w") as file:
                file.writelines(tasks)

            print("Task deleted!")
        else:
            print("Invalid task number.")

    except FileNotFoundError:
        print("No tasks found.")
    except ValueError:
        print("Enter a valid number.")


while True:
    print("\n--- TO-DO LIST MANAGER ---")
    print("1. Add Task")
    print("2. View Tasks")
    print("3. Mark Task Done")
    print("4. Delete Task")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_task()

    elif choice == "2":
        view_tasks()

    elif choice == "3":
        mark_done()

    elif choice == "4":
        delete_task()

    elif choice == "5":
        print("Goodbye!")
        break

    else:
        print("Invalid choice.")

